[functions.telegram-poll]
enabled = true
verify_jwt = false
import_map = "./import_map.json"

[functions.telegram-bot]
enabled = true
verify_jwt = false

[functions.insta]
enabled = true
verify_jwt = false
